[unstable]
build-std           = ["core"]
build-std-features  = ["compiler-builtins-mem"]

[build]
target     = "mipsel-sony-psx"
target-dir = "../../../build/examples"

[target.mipsel-sony-psx]
rustflags = [
    "-Clink-arg=-T../../../sdk/psoxide.ld",
    "-Clink-arg=--oformat=binary",
]
